name: tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install GElib dependencies
      run: |
        python -m pip install --upgrade pip
        # to build cnine and GElib
        pip install wheel
        # torch cpu version
        pip install --extra-index-url https://download.pytorch.org/whl/cpu torch>=2.7.0
        # GElib
        rm python/setup.py
        mv pyproject.toml.new pyproject.toml
        pip install --no-build-isolation -e .[dev]
        cd ..
    - name: Install test dependencies
      run: |
        pip install pytest
    - name: Run tests
      run: |
        pytest python/tests/ci_tests
        #pytest --doctest-modules --pyargs gelib
